apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-issuer-istio-ca
  namespace: istio-system
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: meowhq/vault/approle/istio
      property: role_id
    secretKey: role_id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: meowhq/vault/approle/istio
      property: secret_id
    secretKey: secret_id
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend-cluster-jwt
