apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer-istio-ca
  namespace: istio-system
spec:
  vault:
    server: https://vault.lab.meowhq.dev
    path: "pki/meowhq/istio_int_ca/sign/issuer"
    auth:
      appRole:
        path: meowhq-istio-int-ca-role
        roleId: 17f92c87-35f4-d496-db29-8c236cc1651e
        secretRef:
          name: vault-issuer-istio-ca
          key: secret_id
