apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmCharts:
- name: istiod
  namespace: istio-system
  releaseName: istio
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.21.2
  includeCRDs: true
  valuesFile: values.yaml
