# Istiod Helm Values
# https://istio.io/latest/docs/setup/install/helm/#values-to-override

meshConfig:
  defaultConfig:
    proxyMetadata:
      # Enable basic DNS proxying
      ISTIO_META_DNS_CAPTURE: "true"
      # Enable automatic address allocation, optional
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  accessLogFile: /dev/stdout
global:
  caAddress: "cert-manager-istio-csr.istio-system.svc:443"
  meshID: "meowhq-mesh"
  network: "meowhq-k3s-bee2"
  multiCluster:
    enabled: true
    clusterName: "meowhq-k3s-bee2"
  configValidation: true
  logging:
    level: "default:debug"
  proxy:
    logLevel: debug
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
pilot:
  autoscaleEnabled: false
  env:
    ENABLE_CA_SERVER: false
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
