apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-issuer-istio-ca
  namespace: {{ .Values.istio.namespace }}
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.vault.auth.approle.secretIdSecretPath }}
      property: secret_id
    secretKey: secret_id
  refreshInterval: 60s
  secretStoreRef:
    kind: {{ .Values.vault.secretStoreRef.kind }}
    name: {{ .Values.vault.secretStoreRef.name }}
