---
## ----------------------------------------------------------------------------
## Install istio base and istiod
## ----------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## use custom helm charts to install istio base, istiod, and istio ingress gateways
helmGlobals:
  chartHome: ../../../charts
helmCharts:
- name: meowhq-istio
  namespace: istio-system
  releaseName: istio
  includeCRDs: true
  valuesFile: values.yaml
