---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster-jwt
spec:
  provider:
    vault:
      server: "https://vault.lab.meowhq.dev"
      auth:
        jwt:
          path: "jwt/meowhq-k3s-bee2"
