---
## ----------------------------------------------------------------------------
## Install istio-ca-issuer and istio-csr
## ----------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../packages/istio-ca-issuer   # istio-ca-issuer -- do not apply if you are using manual CA
- ./cert-manager-istio-csr            # cert-manager istio-csr -- do not apply if you are using manual CA
