apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k3s-cluster-dns-tls
  namespace: istio-system
spec:
  secretName: wildcard-k3s-cluster-dns-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - "*.<change-me>.k3s.meowhq.dev"
  issuerRef:
    name: digitalocean-dns-issuer
    kind: ClusterIssuer
