apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmCharts:
- name: base
  namespace: istio-system
  releaseName: istio
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.21.1
  includeCRDs: true
  valuesInline:
    defaultRevision: default
