# istio Cross Cluster Gateway Address Pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: istio-cross-cluster-gateway-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.22
  avoidBuggyIPs: true
  serviceAllocation:
    priority: 50
    namespaces:
      - istio-system
    serviceSelectors:
      - matchLabels:
          app: istio-cross-network-gateway
          istio: cross-network-gateway
