apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../packages/hello-app
- https://raw.githubusercontent.com/sunggun-yu/hello-app/main/manifests/service1.yaml
labels:
- pairs:
    name: meowhq-k3s-bee1
    service: meowhq-k3s-bee1
  includeTemplates: true
  includeSelectors: false
