apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digitalocean-dns-issuer
spec:
  acme:
    email: sunggun.yu@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: digitalocean-dns-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
