apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-api-token
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: meowhq/digitalocean
      property: service-account-cert-acme-token
    secretKey: access-token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend-cluster-jwt
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: digitalocean-dns
