---
## ----------------------------------------------------------------------------
## Install istio-ca-issuer and istio-csr
## ----------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## use custom helm charts to install istio-csr and ca-issuer
helmGlobals:
  chartHome: ../../../charts
helmCharts:
- name: cert-manager-istio-csr
  namespace: istio-system
  releaseName: cert-manager
  includeCRDs: true
  valuesFile: values.yaml
