---
## ----------------------------------------------------------------------------
## Install istio-ca-issuer and istio-csr
## ----------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../packages/istio-gateways         # istio-gateways, ingress and cross-network gateway
