apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmCharts:
- name: istiod
  namespace: istio-system
  releaseName: istio
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.21.1
  includeCRDs: true
  valuesInline:
    global:
      caAddress: "cert-manager-istio-csr.istio-system.svc:443"
      meshID: "meowhq-mesh"
      network: "meowhq-k3s-xeon2"
      multiCluster:
        enabled: true
        clusterName: "meowhq-k3s-xeon2"
    pilot:
      env:
        ENABLE_CA_SERVER: false
