# =============================================================================
# global configuration for all components including istio sub-charts
# =============================================================================
global:
  istioNamespace: istio-system
  priorityClass: infra-critical

# =============================================================================
# istio base Helm Chart configuration
# =============================================================================
base:
  enabled: true
  defaultRevision: default

# =============================================================================
# istiod Helm Chart configuration
# =============================================================================
istiod:
  enabled: true
  # global configuration for istiod
  # istiod.global can be configured under global section
  global:
    # ------------------------------------------------------------------------
    # below for the istio-csr integration for Vault PKI - istio multicluster setup
    # istiod.global.caAddress: "cert-manager-istio-csr.istio-system.svc:443"
    # ------------------------------------------------------------------------
    caAddress: "cert-manager-istio-csr.istio-system.svc:443"

    # ------------------------------------------------------------------------
    # below for the istio multicluster setup
    # istiod.global.meshID: "change-me-to-the-mesh-name"
    # istiod.global.network: "change-me-to-the-cluster-name"
    # istiod.global.multiCluster.enabled: true
    # istiod.global.multiCluster.clusterName: "change-me-to-the-cluster-name"
    # ------------------------------------------------------------------------
    meshID: "meowhq-mesh"
    network: "meowhq-k3s-xeon1"
    multiCluster:
      enabled: true
      clusterName: "meowhq-k3s-xeon1"

  pilot:
    ## ------------------------------------------------------------------------
    ## below for the istio-csr integration for Vault PKI - istio multicluster setup
    ## ------------------------------------------------------------------------
    env:
      ENABLE_CA_SERVER: false

# =============================================================================
# istio-gateway Helm Chart configuration : Ingress Gateway
# (aliased as ingressgateway)
# =============================================================================
ingressgateway:
  enabled: true
  # service:
  #   loadBalancerIP: ""

# =============================================================================
# istio-gateway Helm Chart configuration : Cross Network Gateway
# (aliased as cross-network-gateway)
# -----------------------------------------------------------------------------
# this gateway is for istio multicluster setup
# =============================================================================
cross-network-gateway:
  enabled: true
  networkGateway: meowhq-k3s-xeon1
  # service:
  #   loadBalancerIP: ""
